platform :ios, ‘9.3’
inhibit_all_warnings!

pod 'AFNetworking'
pod 'ReactiveCocoa', '2.5'
pod 'ReactiveViewModel'
pod 'Mantle', '2.0'
pod 'Typhoon'

target :MarvelTests, :exclusive => true do
    pod 'RamblerTyphoonUtils/AssemblyTesting'
end